language: python
env:
matrix:
  include:
  - python: "2.7"
    env: REQUIREMENTS=requirements27.txt
  - python: "3.6"
    env: REQUIREMENTS=requirements.txt
 
# command to install dependencies
install: pip install -r $REQUIREMENTS

# command to run tests
script: python -m unittest discover

# command to run coveralls
after_success:
  - coveralls
